Fix certificate validity check (#9037)
* Fix certificate validity check

Use 'not_valid_after_utc' instead of 'not_valid_after' when checking for certificate validity to prevent errors with avare/naive timedates

Fixes error:

File "<>\site-packages\celery\security\certificate.py", line 46, in has_expired
    return datetime.datetime.now(datetime.timezone.utc) >= self._cert.not_valid_after
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes

* Fix tests