Fixed AttributeError: 'str' object has no attribute (#8463)
* Fixed looping through tasks instead of going through the tasks's dict keys.
Prevents error like:
AttributeError: 'str' object has no attribute 'link_error'

* Added automatic tests

* Fixed looping through link/link_error instead of going through dict keys.
Prevents error like:
AttributeError: 'str' object has no attribute '_app'

* Added automatic tests